export const GET_SONGS = 'GET_SONGS';
export const RESET_YT = 'RESET_YT';
export const SET_YT_PLAY = 'SET_YT_PLAY';
export const TOGGLE_GROUPCHANNELS = 'TOGGLE_GROUPCHANNELS';
export const TOGGLE_SORTDATENEWEST = 'TOGGLE_SORTDATENEWEST';
export const TOGGLE_LAYOUT = 'TOGGLE_LAYOUT';
export const TOGGLE_CHANNEL = 'TOGGLE_CHANNEL';
export const TOGGLE_CHANNEL_SELECTALL = 'TOGGLE_CHANNEL_SELECTALL';