export const GET_SONGS = 'GET_SONGS';
export const RESET_YT = 'RESET_YT';
export const SET_YT_PLAY = 'SET_YT_PLAY';
export const TOGGLE_GROUPCHANNELS = 'TOGGLE_GROUPCHANNELS';
export const TOGGLE_SORTDATENEWEST = 'TOGGLE_SORTDATENEWEST';